name: Market Scanner Update
on:
  schedule:
    - cron: '*/10 * * * *' # हर 10 मिनट में अपडेट होगा
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install yfinance pandas-ta
      - name: Run scanner
        run: python bot.py
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add market_scan.json
          git commit -m "Automated Market Scan Update" || echo "No changes"
          git push
